name: CI Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  cache:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: create test caches
        run: |
          echo "test1" | tee file1.txt
          echo "test2" | tee file2.txt
          echo "test3" | tee file3.txt

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: file1.txt
          key: test-cache-old-${{ github.run_id }}

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: file2.txt
          key: test-cache-new-${{ github.run_id }}

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: file3.txt
          key: test-cache-recent-${{ github.run_id }}

  test-normal-mode:
    name: Test normal mode (time-based)
    runs-on: ubuntu-latest
    needs: cache
    if: github.repository_owner == 'luxass'
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: wait 10 seconds
        run: sleep 10

      - name: purge old caches (older than 10 seconds)
        uses: luxass/purge-action-cache@main
        with:
          mode: normal
          debug: "true"
          max-age: 10
          filter-key: last_accessed_at

  test-normal-mode-created-at:
    name: Test normal mode with created_at filter
    runs-on: ubuntu-latest
    needs: cache
    if: github.repository_owner == 'luxass'
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: wait 5 seconds
        run: sleep 5

      - name: purge caches using created_at filter
        uses: luxass/purge-action-cache@main
        with:
          mode: normal
          debug: "true"
          max-age: 5
          filter-key: created_at

  test-normal-mode-with-ref:
    name: Test normal mode with specific ref
    runs-on: ubuntu-latest
    needs: cache
    if: github.repository_owner == 'luxass'
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: purge old caches for current ref
        uses: luxass/purge-action-cache@main
        with:
          mode: normal
          debug: "true"
          max-age: 3600
          ref-key: ${{ github.ref }}

  test-all-mode:
    name: Test all mode
    runs-on: ubuntu-latest
    needs: [test-normal-mode, test-normal-mode-created-at, test-normal-mode-with-ref]
    if: github.repository_owner == 'luxass'
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: purge all remaining caches
        uses: luxass/purge-action-cache@main
        with:
          mode: all
          debug: "true"
